language: cpp
env:
    - RACK_VER="v0.6.2b" RACK_DIR="$TRAVIS_BUILD_DIR/Rack"
addons:
    apt:
        packages:
            - git
            - curl
            - cmake
            - libx11-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - zlib1g-dev
            - libasound2-dev
            - libgtk2.0-dev
            - libjack-jackd2-dev

install: $TRAVIS_BUILD_DIR/travis-install-rack.sh

script:
    - make dep
    - make
    - make dist

cache:
    directories:
        - Rack
